# Generated by Django 3.1 on 2020-08-27 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adtypes',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('type_name', models.CharField(max_length=50)),
                ('Is_deleted', models.BooleanField()),
            ],
        ),
    ]
