# Generated by Django 3.1 on 2020-08-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField(max_length=256)),
                ('is_deleted', models.BooleanField(default=0)),
                ('commented_user', models.ManyToManyField(blank=True, related_name='commented_user', to='feedback_model.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_model.user')),
            ],
        ),
    ]
