# Generated by Django 3.1 on 2020-08-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('ad_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(default=None, max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ad_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imageModel.ad')),
            ],
        ),
    ]
