# Generated by Django 3.1 on 2020-08-25 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdManagerApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('ad_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='promotion_package',
            fields=[
                ('promotion_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='promotion_ad_details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='promotion_ad_details',
            name='title',
        ),
        migrations.AddField(
            model_name='promotion_ad_details',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='promotion_ad_details',
            name='pa_ad_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='promotion_ad_details',
            name='starting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promotion_ad_details',
            name='status',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='promotion_ad_details',
            name='ad_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdManagerApi.ad'),
        ),
        migrations.AddField(
            model_name='promotion_ad_details',
            name='promotion_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AdManagerApi.promotion_package'),
        ),
    ]
