# Generated by Django 3.1 on 2020-08-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=0)),
                ('commented_user', models.ManyToManyField(blank=True, related_name='commented_user', to='category.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.user')),
            ],
        ),
    ]
